[package]
name = "my_rust-bert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.21.0"
tch = "0.13.0"
anyhow = "1.0.72"
